### ISSUE TITLE
UI Refactoring

### ISSUE THREAD

**Issue by papachristoumarios** [eellak/gsoc2018-3gm#3]
Change UI as follows:

`codify_law.html`

## Τρέχουσα Μορφή του ν. 1234/4325
*  Σύνδεσμος Για ιστορικό Εκδόσεων
* Ποιοι νόμοι τον τροποποιούν + hyperlinks
* (Optionally) Ποιους νόμους τροποποιεί.
* Ετικέτες και παρόμοια θεματολογία

`history.html`
Accordion elements 

### Ο ν. 4009/2011 όπως ισχύει σήμερα

# Ιστορικό
## Ευρετήριο
* ν. 4485/2017
* ν. 4405/2016
* ν. 4310/2014
* ...
* Αρχική μορφή του ν. 4009/2011

### ν. 4485/2017
... (κείμενο των αλλαγών)
(Δεσμός:) [Εμφάνιση του ν. 4009/2011 μέχρι και τις αλλαγές του ν. 4485/2017]
Απόσπασμα Συνδέσμων + Status εφαρμογής. 

### ν. 4405/2016
... (κείμενο των αλλαγών)
(Δεσμός:) [Εμφάνιση του ν. 4009/2011 μέχρι και τις αλλαγές του ν. 4405/2016]

### ν. 4310/2014
... (κείμενο των αλλαγών)
(Δεσμός:) [Εμφάνιση του ν. 4009/2011 μέχρι και τις αλλαγές του ν. 4310/2014]

**Comment by dspinellis** [comment]
Small change:

## Ευρετήριο

* Αλλαγές βάσει του  ν. 4485/2017
* Αλλαγές βάσει του ν. 4405/2016

**Comment by papachristoumarios** [comment]
Sample Mock (ignore years and dates):

![screenshot_2018-07-13_19-40-27](https://user-images.githubusercontent.com/918216/42703222-a32c8038-86d4-11e8-845c-481cf080fd3d.png)

**Comment by dspinellis** [comment]
LGTM; nice!  Please use the wording "Εμφάνιση του ν. 4009/2011 μέχρι και τις αλλαγές του ν. 4405/2016".  Also, the tags are not very clear to an outsider. Please expand, or provide detailed bubble help.

**Comment by papachristoumarios** [comment]
Commit: c98a0cc91144b3b68352dee2725c2e1999fea4f1
The need for help page is opened as a separate issue
