### ISSUE TITLE
3gm.ellak.gr

### ISSUE THREAD

**Issue by ellakdev** [eellak/gsoc2018-3gm#8]
Please configure 3gm.ellak.gr to work with the VM at 83.212.109.156 .

**Comment by papachristoumarios** [comment]
This s my nginx `virtual.conf` on the virtual machine 83.212.109.156:
```
server {
    listen       80;
    server_name  3gm.papachristoumarios.me 3gm.ellak.gr openlaws.ellak.gr;	

    location / {
        proxy_pass http://127.0.0.1:8000;  
    }
}
```
The first domain is fully working under the same configuration. 
Is there anything else missing from the conf? 

Kind regards,
Marios

**Comment by papachristoumarios** [comment]
Problem solved. The server wasn't configured to work with HTTPS.
